### ISSUE TITLE
API Token Regex Incorrect

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn-contrib/job-executor-service#159]
Keptn API Tokens can contain `+` so deploying via helm fails when API tokens contain forbidden chars.

https://github.com/keptn-contrib/job-executor-service/blob/b3eeccef1da6f8dfa873916188ed470a6463b56f/chart/values.schema.json#L44

**Comment by pchila** [comment]
Thanks @Dynatrace-Adam-Gardner for the spotting the issue and providing the fix :) PR merged
