### ISSUE TITLE
Add liveness/readiness probes for job-executor service

### ISSUE THREAD

**Issue by pchila** [keptn-contrib/job-executor-service#174]
In PR #173 The old liveness and readiness probes had to be removed since the distributor is only listening on `localhost` and job-executor doesn't spin up an HTTP server so the `/health` endpoint handled by the distributor is not reachable (the pod would be continuously restarted by k8s due to the probe failure).

We need to introduce an endpoint reachable from k8s that is able to check for both `job-executor` and `distributor` (maybe this one can be done through a forward to `http://localhost:8081/health`) liveness and readiness.

/cc @agrimmer @christian-kreuzberger-dtx

**Comment by christian-kreuzberger-dtx** [comment]
distributors health endpoint has been removed for 0.12.x, so yeah, that's expected.

IMO we should consider introducing `/health` for job-executor
