### ISSUE TITLE
Introduce gotestsum

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/job-executor-service#186]
Keptn Core has successfully introduced gotestsum, e.g.: https://github.com/keptn/keptn/pull/6803

We should also introduce it, as it will make the output of our unit tests much cleaner, e.g.:
![image](https://user-images.githubusercontent.com/56065213/156355451-1d75245a-7843-4066-a212-40869ecd2af6.png)

# Definition of Done

- [ ] Use `gotestsum` in our unit test workflow/action

**Comment by mehabhalodiya** [comment]
I am a beginner with this but still I am happy to help. Let me know where and what needs to be changed?
Thanks!

**Comment by christian-kreuzberger-dtx** [comment]
Appreciate the help. I'd like to keep this issue for our core maintainers, as it involves a bit more knowledge about the repo, GH actions etc... :)
