### ISSUE TITLE
RFE: Change init container pullPolicy

### ISSUE THREAD

**Issue by pchila** [keptn-contrib/job-executor-service#191]
At the moment we specify  [imagePullPolicy=Always](https://github.com/keptn-contrib/job-executor-service/blob/567b8b8bb615c0af6bb9fded8d4a0c8c678dcf9f/pkg/k8sutils/job.go#L121) for the init container image of all jobs that are spawned.
This is wasteful since most of the time we are trying to pull the same image (unless the init container image has some sort of special moving tag like `latest`) and it can be annoying when developing with skaffold and k3d (we need to modify the code just to get things going).
Can we change it to `IfNotPresent` (default in k8s for any non-empty, non-latest tag) or at least make it configurable when deploying the service or running the job ?

/cc @christian-kreuzberger-dtx  @Raffy23

**Comment by mehabhalodiya** [comment]
I am a forst-time contributor. I would like to work on this. Will you please assign it to me?
Thanks.

**Comment by christian-kreuzberger-dtx** [comment]
@mehabhalodiya any updates?

**Comment by mehabhalodiya** [comment]
> @mehabhalodiya any updates?

Sorry for the delay!
I have made a PR now. Please review it. Thanks!
