### ISSUE TITLE
Read-only file system

### ISSUE THREAD

**Issue by agardnerIT** [keptn-contrib/job-executor-service#253]
I'm trying to do create a directory and file inside a JES pod. Is it possible to allow writing?

Further details:

I’m trying to do a `git clone` then create a file and the commit and push. I’m NOT pushing to the Keptn repo, but to an entirely different one.

More generically, the use case would be writing files (that I’m processing temporarily into the container) that can and should vanish when the container ends.

**Comment by christian-kreuzberger-dtx** [comment]
Related slack thread https://keptn.slack.com/archives/CGS5TA283/p1652953349690819

By default, job-executor uses read-only file-system. You can play around with the configurations:

* Global (during installation): https://github.com/keptn-contrib/job-executor-service/blob/2ca699edd9ba18bd747ecd51f9b572c78b39da7a/chart/values.yaml#L62-L72
* Per job: https://github.com/keptn-contrib/job-executor-service/blob/main/FEATURES.md#job-security-context
* Generally speaking: Try writing into the `/keptn` directory

**Comment by darkgordon** [comment]
Thank you very much @agardnerIT for your help I will check it out
