### ISSUE TITLE
Can JES listen for get-sli.triggered?

### ISSUE THREAD

**Issue by agardnerIT** [keptn-contrib/job-executor-service#323]
Is it possible for Job Executor Service to listen for `sh.keptn.event.get-sli.triggered`?

I'd like to use JES to implement an SLI provider.

I have it listening (apparently) for the event but cannot get it to "fire". Presumably because all other "shipyard defined tasks" are distributed by the shipyard-controller and this one is sent directly from the lighthouse service. So JES never "hears" it?

```
{
...
"source": "lighthouse-service",
  "specversion": "1.0",
  "time": "2022-07-18T04:31:17.01614488Z",
  "gitcommitid": "ae5132563700eaa6f947531272eef422ba9f8f4c",
  "type": "sh.keptn.event.get-sli.triggered"
...
}
```

**Comment by christian-kreuzberger-dtx** [comment]
Probably not possible.

Nothing special about the event from job-executor site, but I'm assuming that Keptn's shipyard-controller directly sends this event to NATS, therefore it's not processed by shipyard-controller, and therefore job-executor will never be triggered.
See https://github.com/keptn/enhancement-proposals/pull/56 for more details.
