### ISSUE TITLE
Include all keptn versions in integration tests markdown report

### ISSUE THREAD

**Issue by pchila** [keptn-contrib/job-executor-service#326]
There have been a few integration test runs where not all keptn version are displayed in the markdown report (both in the action run and in the related issues, for example:
[this issue](https://github.com/keptn-contrib/job-executor-service/issues/324) and the  [related run](https://github.com/keptn-contrib/job-executor-service/actions/runs/2695122727) do not include anything about the 0.17.0 release and prerelease runs.

All keptn version we test against should be displayed in the report regardless if they are "static" versions or dynamically discovered latest release and prerelease.

**Comment by christian-kreuzberger-dtx** [comment]
Just double checked, and it's because the 0.17 tests have failed too early during installation, and did write
```
{"Test": "TestGitHub Pipeline", "Action": "fail"}
```
into the test report, intead of an actual log. I guess that this case is not handled very well.
