### ISSUE TITLE
JES detects JSON in log output and sends in finished event

### ISSUE THREAD

**Issue by agardnerIT** [keptn-contrib/job-executor-service#335]
Assume the JES runs an image that outputs the following for `myTask.triggered`:

```
here is your output { "foo": "bar" }
```
Currently this entire thing is reported as a string. Is it technically feasible for JES to read that content and then we can detect that it contains JSON and send in the finished event:

```
{
  "type": "sh.keptn.event.myTask.finished",
  "data": {
    "myTask": {
      "foo": "bar"
    }
  }
}
```

Obviously we're assuming here (or perhaps can add checks) that the JSON is valid.

**Comment by Raffy23** [comment]
I think trying to automatically detect the output format of the tasks isn't something that JES should do. It is probably better to specify a property in the job configuration that indicates the type of the expected output and use that in the future to parsing.
 
But even with such a property, it currently isn't possible to attach any form of structured output to a .finished Event in JES, which we would need for this to work.

**Comment by christian-kreuzberger-dtx** [comment]
It sounds so straight forward and simple, and I have already discussed this with multiple people. I would really love to have exactly this functionality.

Unfortunately, as @Raffy23 already pointed out, it's not simple to implement and could break other uses of job-executor. As a first example, there could be multiple tasks within a job config that are executed, and we would only be able to take the result of the last one.

In addition, just guessing the output could be very problematic, e.g., what would `[]` result to? It's a valid JSON output, but how would you add it?
