### ISSUE TITLE
Question about PVC in JES

### ISSUE THREAD

**Issue by darkgordon** [keptn-contrib/job-executor-service#385]
Hello guys,
I have a question regarding the job execution service. I use this service to do some jmeter testing it works like a charm but recently I created a custom new task, in this task I verify the git repository by downloading it and execute some commands.
In this case When it is executed, I receive an error regarding the use of my filesystem not being able to write, so I can’t save the git repository when doing an git clone for example.
It is possible for the job-executor-service-job template to add some persistence volume? for the pods that are executed.

**Comment by agardnerIT** [comment]
https://github.com/keptn-contrib/job-executor-service/issues/253

**Comment by darkgordon** [comment]
Thank you very much @agardnerIT for your help I will check it out

**Comment by darkgordon** [comment]
Thank you @agardnerIT  I achieve the desired task in keptn
