### ISSUE TITLE
Bring up a way to share integrations

### ISSUE THREAD

**Issue by tolleiv** [keptn-contrib/job-executor-service#58]
Hi,

I'd suggest to bring up some way or template on how existing integrations could be shared.

E.g. I implemented a helm-service replacement with the job-executor-service but I'd rather not push that into the README (to keep it reasonable small) or a blog-post (which would be invisible for new users) . It would be great if there was a spot where these could be shared easily.

Cheers

**Comment by jetzlstorfer** [comment]
Hi, 
thanks for bringing this up. I think we can address this with our efforts to include Keptn integrations in the artifact hub. I've not yet put a lot of thoughts into how to display integrations via the job-executor but they definitely should get a public stage to be shared and highlighted.

**Comment by didiladi** [comment]
@tolleiv that's a great idea! I also like the idea of @jetzlstorfer to have them in the artifact hub at some point! :rocket:

For now, how about having a dedicated github discussion (or discussion type) in this repository where people can add their examples? I'll put something together in this, or next week and post our current examples (API tests (RestAssured) diven by junit + terraform) there.

**Comment by christian-kreuzberger-dtx** [comment]
I also would say for now please create a new [GitHub Discussion](https://github.com/keptn-contrib/job-executor-service/discussions) with a quick description + example of how to use it :)

**Comment by christian-kreuzberger-dtx** [comment]
We will come up with a way to share integrations with job-executor-service on https://github.com/keptn-sandbox/artifacthub

**Comment by tolleiv** [comment]
This sounds great - I'm not even sure if this issues is still required - it was just meant to show you that is a topic of interest. So feel free to close it in case it doesn't serve any purpose for you.

**Comment by christian-kreuzberger-dtx** [comment]
For the purpose of tracking progress I will keep it open until we have a first example in the artifacthub repo ;)

**Comment by christian-kreuzberger-dtx** [comment]
Integrations are shared on artifacthub.
Examples:
* https://github.com/keptn-contrib/artifacthub/pull/90
* https://github.com/keptn-contrib/artifacthub/tree/main/jmeter/0.1.0
