### ISSUE TITLE
Silent mode for events in non-remote execution planes does not work

### ISSUE THREAD

**Issue by yeahservice** [keptn-contrib/job-executor-service#95]
The following if prevents processing of any non `.triggered` events and therefore the silent mode can't really be used.

```
	if !strings.Contains(event.Type(), ".triggered") {
		return nil
	}
```
see https://github.com/keptn-contrib/job-executor-service/blob/be2956e0aeebeaa5c69b883131ca2dee91b235ba/cmd/job-executor-service/main.go#L86

It would probably be best to remove the if and completely test the silent mode.

**Comment by TannerGilbert** [comment]
I'll work on this
